name: Feature Request
description: Suggest a new feature or enhancement for TASKquence
title: "[FR]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

        Please provide as much detail as possible. 

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Please describe your feature request
    validations:
      required: true

