import type TaskNotesPlugin from "../main";

export const GOAL_COPY_KEYS = [
	"management",
	"newGoal",
	"refresh",
	"paused",
	"emptyTitle",
	"emptyDescription",
	"createGoal",
	"cancel",
	"name",
	"type",
	"floor",
	"ceiling",
	"count",
	"floorHint",
	"ceilingHint",
	"countHint",
	"scope",
	"addTag",
	"baseline",
	"split",
	"period",
	"weekly",
	"monthly",
	"quarterly",
	"target",
	"milestone",
	"milestoneName",
	"tiers",
	"files",
	"created",
	"createFailed",
	"noGoals",
	"allGoals",
	"why",
	"children",
	"progress",
	"thisWeek",
	"thisMonth",
	"thisYear",
	"remaining",
	"achieved",
	"onTrack",
	"behind",
	"over",
	"idle",
	"aggregate",
	"noMilestone",
	"confirmAchievement",
	"confirmAchievementDescription",
	"continue",
	"undo",
	"openFile",
	"notDesktop",
] as const;

export type GoalCopyKey = (typeof GOAL_COPY_KEYS)[number];

export function goalCopy(plugin: TaskNotesPlugin, key: GoalCopyKey): string {
	return plugin.i18n.translate(`goals.${key}`);
}
